NativeScript/firebase

packages/firebase-auth/README.md, packages/firebase-messaging/README.md
Whilst migrating to this new library I've noticed some discrepancies in the documentation. Mainly with the authentication flows particularly:
1. Updated the facebook authentication flow
2. Updated the google authentication flow
3. Small change to the messaging documentation
=> Updates to documentation

packages/firebase-functions/README.md, packages/firebase-functions/index.android.ts, packages/firebase-functions/index.d.ts, packages/firebase-functions/index.ios.ts
Add client-side location selection for callable functions.
Allow App functions to call Cloud Functions with a selectable Region (Android & iOS) or Custom Domain (iOS only); e.g. functions created for region "europe-west2".
Otherwise, all Firebase Functions calls are to the default "us-central1" region.
=> Implement client-side Firebase Cloud Functions locations

packages/firebase-analytics/index.d.ts
Ran into the following error when using the analytics plugin in a NativeScript Angular project in an Nx workspace.
```bash
Property 'analytics' does not exist on type 'Firebase'.ts(2339)
```
This happens when I try to access the `analytics` function from the `firebase` function.
```typescript
firebase().analytics()
```
This PR adds the missing `Firebase` import in the `firebase-analytics`'s `index.d.ts` file. :)
=> bug(analytics): add missing Firebase import from analytics index.d.ts

packages/firebase-messaging/index.ios.ts
I have a custom "data" field which contains a "payload" object with additional data when I'm sending an FCM message. I noticed that the "payload" data didn't get parsed correctly in the `parseRemoteMessage` function which resulted in the entire "payload" data to be missing as it reaches the app.
Troubleshooting it further, I found that two of the `if` statements with square brackets is always returning `true` which resulted in the "payload" data being missing.
=> bug(messaging): fix parsing remote message

packages/firebase-crashlytics/index.android.ts, packages/firebase-crashlytics/index.ios.ts
If an Error's stack trace contains stack information about an arrow function `() => ...` then `stacktrace-js` will not create a `functionName` entry for that element. At least on Android, this leads to a runtime error.
Proposal: if the `functionName` is empty, use `(anonymous)` as the function name.
fixes #65
=> fix: use (anonymous) for empty functionNames when generating stack information in recordError()

packages/firebase-messaging/src-native/android/messaging/src/main/java/org/nativescript/firebase/messaging/FirebaseMessaging.kt
I believe that this solves the issue where if there are multiple notifications recieved when the app is closed, 
Clicking on the first notification opens the app and the app gets the message, but if you then close the app and then click the next notification the app does not recieve the events.
Note:  I'm not sure how you are producing the platforms/android/messaging-release.aar so I've only checked in the kotlin.
This is from this discussion:  https://discordapp.com/channels/603595811204366337/751068755206864916/954024742233464862
=> fix(messaging): prevent loss of messages when app is closed.

packages/firebase-dynamic-links/platforms/ios/src/TNSFirebaseDynamicLinksAppDelegate.swift
Apparently the options are always empty https://github.com/firebase/firebase-ios-sdk/blob/136e71f7aa438236421307a69c01789855515464/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L544
=> fix(dynamic-links): prevent crash when annotation is null

packages/firebase-messaging/index.d.ts
Seems like it can't figure out the typings for things which are directly exported when they are used in the type definitions.
So need to import and then export.
=> fix(messaging): Typings for reexported Types that are used in the method definitions.

packages/firebase-admob/utils.ts
Fix getting the rootViewController on iOS in complex situations.
References issue #137
=> Fix #137 - Getting rootViewController on iOS

packages/firebase-firestore/index.ios.ts
This PR resolves the following issue:
Performing an update with a FIeldValue used as a nested property value such as:
```typescript
await firebase.firestore().doc('test/1234').update({
a: {
b: FieldValue.serverTimestamp()
}
})
```
Results in the following firestore document contents:
=> fix(firestore): iOS nested FieldValues not serialized in update()

packages/firebase-firestore/common.ts, packages/firebase-firestore/index.android.ts, packages/firebase-firestore/index.d.ts, packages/firebase-firestore/index.ios.ts
While I had mainly written this refactor to address bugs that were probably addressed in ba384c21ff6384e9db365ed5c21281b1da9ec5ff and c74f67a90e68fd69fbc823016ad9c6305bbc687f, I still believe this is worth submitting as the current onSnapshot handler implementations are very difficult to understand due to parameter names and overloads. This refactor aims to address the issue of parsing the parameters (with full type checking) centrally in a single `parseOnSnapshotArgs` helper, after which we can implement the actual handling logic in a way that looks much more intuitive in the individual onSnapshot methods.
=> chore: cleanup onSnapshot implementations

packages/firebase-firestore/index.android.ts, packages/firebase-firestore/index.d.ts, packages/firebase-firestore/index.ios.ts, packages/firebase-firestore/platforms/ios/Podfile
This PR adds the `isEqual` method on the Query class and replaces the pod source to use invertase/firestore-ios-sdk-frameworks's pre-compiled .xcframeworks. This change yielded compile time improvements similar to those seen in the [project's readme](https://github.com/invertase/firestore-ios-sdk-frameworks) for my project. This is due to not having to compile several hefty frameworks (FirebaseCore, abseil, gRPC-C++, leveldb-library, nanopb) as part of the build process.
**Mac mini (2018) 6 cores:**
Before:    ~ 240s
After:     ~  45s
=> Firestore improvements

packages/firebase-messaging-core/README.md, packages/firebase-messaging/README.md
When placing the file `YourAppName.entitlements in app/App_Resources/iOS/` I noticed Apple sign in and push notifications both stopped working. It appears the entitlements file should actually be called app.entitlements to be picked up by the cli. This PR corrects the advice given in the Messaging Readme.
**Tested with**
NativeScript CLI "version": "8.0.2"
Platform MacOS
=> fix(messaging): readme file rename instructions do not work

packages/firebase-auth/index.ios.ts, packages/firebase-auth/typings/objc!FirebaseAuth.d.ts
This PR fixes an issue where all properties of providerData values on the user were appearing as `undefined` on iOS e.g.
```
console.log(firebase.auth().currentUser.providerData[0].toJSON())
```
produces
```
{
displayName: undefined
email: undefined
phoneNumber: undefined
photoURL: undefined
providerId: undefined
uid: undefined
}
```
=> fix(auth): ios providerData properties undefined

packages/firebase-core/utils.ts
Firebase analytics' `logEvent` method fails on iOS when there's an array with null/undefined elements and when objects have null/undefined prop values. 
With this PR the null elements are filtered out of arrays and dictionaries.
This PR also fixes a slight oversight with `data.map(serialize)`, since this syntax causes the second argument to be the element index instead of `wrapPrimitives`, causing the first element not to be wrapped and all the others to be.
```ts
firebase().analytics().logEvent('eventname', [ null, undefined ]);
// Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] Error: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]
firebase().analytics().logEvent('eventname', { …
```
=> fix(ios/core): filter out nil values from `serialize` method

packages/firebase-messaging-core/index.android.ts
This is a fix for what I described in issue #152 . It seems we call `register()` when activities get created so we have to take precautions for activities who do not support activity result API.
Still, I wonder if we should just ignore those activities or treat them differently.
Fixes #152 https://github.com/NativeScript/payments/issues/19
=> fix(messaging): Activity registerForActivityResult is not a function

packages/firebase-dynamic-links/index.android.ts, packages/firebase-dynamic-links/index.d.ts, packages/firebase-dynamic-links/index.ios.ts
`ShortLinkType` is exported only as a type in the `index.d.ts` file, but since it is an enum it should be exported as a value too, otherwise get errors like: `Cannot read property 'UNGUESSABLE' of undefined`
=> fix(dynamic-links): export ShortLinkType as an object

packages/firebase-dynamic-links/index.android.ts
`_build()` was only called for short links, this caused long links to not respect the values for `analytics`, `android`, `ios`, `itunes`, `navigation`, and `social` props.
=> fix(dynamic-links): build link before generating long link

packages/firebase-analytics/hooks/before-checkForChanges.ts, packages/firebase-analytics/platforms/ios/Podfile
Some context:
Before we would find the platforms/ios/Podfile and add $NSFirebaseAnalyticsWithoutAdIdSupport to the top. Turns out that the file is not always available on before-checkForChanges and it's only available consistently in after-prepare, which is already too late (pods already installed). As a result, the first build would not have the option, and from the second build onwards it would.
So instead of adding another hook to the cli, I simply modify the Podfile in node_modules. The code is resilient enough to always update the Podfile if the desired result is different from the current state (if `$NSFirebaseAnalyticsWithoutAdIdSupport=true` in the user Podfile, it will add to the plugin Podfile if missing. If `NSFirebaseAnalyticsWithoutAdIdSupport=true` is present in the plugin …
=> fix(firebase-analytics): consistent handling of Podfile variable $NSFirebaseAnalyticsWithoutAdIdSupport

packages/firebase-crashlytics/index.ios.ts
The `traceElements` variable was being initialized but not used anywhere. This PR sets the stacktrace in the FIRExceptionModel and also sets the error name to match the JS error name.
=> fix(crashlytics/ios): record stacktrace for JS errors

packages/firebase-dynamic-links/src-native/android/dynamic_links/src/main/java/org/nativescript/firebase/dynamic_links/FirebaseDynamicLinks.kt
This PR fixes the following error when calling `resolveLink` on android:
```
Error: java.lang.IllegalArgumentException: FDL domain is missing. Set with setDomainUriPrefix() or setDynamicLinkDomain().
```
I imagine that the buildShortDynamicLink is either a leftover from older code or was pasted by accident in that method implementation.
=> fix(dynamic-links): IllegalArgumentException on resolveLink

packages/firebase-dynamic-links/common.ts, packages/firebase-dynamic-links/index.android.ts, packages/firebase-dynamic-links/index.d.ts, packages/firebase-dynamic-links/index.ios.ts, packages/firebase-dynamic-links/platforms/ios/src/TNSFirebaseDynamicLinksAppDelegate.swift
This PR adds an optional parameter to the `onLink` handler that indicates the error that occurred while fetching the target of a short dynamic link.
There are two reasons for this change:
- This makes both iOS and Android behave the same for unknown links. Right now the Android handler emits null for unknown links, while iOS simply ignores them.
- The error is useful for applications that need to show some sort of user message or dispatch an event upon malformed or unknown dynamic links.
**BREAKING CHANGE:** This change will call the dynamic link handler with null values on iOS. For Android, it'll be the same as before since the error param is optional.
=> feat(dynamic-links): forward errors to application

packages/firebase-messaging/README.md
I think in the table showing when a notification will be displayed the titles should be shifted over to the right like this.
=> Update notification table Firebase Messaging README.md 

packages/firebase-auth/README.md, packages/firebase-auth/index.android.ts, packages/firebase-auth/index.d.ts, packages/firebase-auth/index.ios.ts
Hi @NathanWalker @triniwiz 
this is a PR in case you agree about #174.
=> [auth][android] resolve signOut return undefined #174

packages/firebase-messaging-core/README.md, packages/firebase-messaging-core/index.d.ts, packages/firebase-messaging/README.md
I have added these properties to the class and I have also added it in the documentation and corrected the import of AuthorizationStatus
=> Expose inForeground and appDidLaunch

packages/firebase-core/README.md
I don't believe it is currently communicated clearly that `@nativescript/firebase-core` cannot initialize successfully on it's own.
@nativescript/firebase-core initialization code
```
const defaultApp = firebase().initializeApp().then(() => {
console.warn('🔥 Firebase initialized');
}).catch(error => {
console.error('🔥 Firebase initialization error: ', error)
});
```
fails on android with: `Error: Cannot read properties of undefined (reading 'FirebaseApp')`
fails on iOS with: `Error: FIRApp is not defined`
Installing plugin `@nativescript/firebase-messaging`, I assume any other would work too, makes the initialization a success
=> Update README.md highlighting dependency on sibling plugins

packages/firebase-analytics/index.android.ts
mimicks iOS logic and uses long or double as defined in the android docs
=> fix(analytics): long/double handling for android

packages/firebase-app-check/platforms/android/include.gradle
SafetyNet is deprecated and no longer accepts new projects. New projects should use App Check with Play Integrity instead and existing apps using SafetyNet should migrate to Play Integrity before the shutdown deadline. See the deprecation timeline for more information. App Check will continue to support existing SafetyNet projects until June 2023, after which, SafetyNet configurations will be frozen and unmodifiable. After June 2024, all SafetyNet features will be permanently shut down and removed.
=> Update include.gradle with Play Integrity

packages/firebase-messaging-core/index.ios.ts, packages/firebase-messaging-core/platforms/ios/src/NSCFirebaseMessagingCore.h, packages/firebase-messaging-core/platforms/ios/src/NSCFirebaseMessagingCore.m, packages/firebase-messaging-core/platforms/ios/src/NSCUIApplicationDelegate.swift, packages/firebase-messaging-core/platforms/ios/src/NSCUNUserNotificationCenterDelegate.swift, packages/firebase-messaging/typings/objc!NSCFirebaseMessagingCore.d.ts
On iOS, after all registered callbacks for `onMessage` and `onNotificationTap` events are triggered, the `completionHandler` is called. However, when a callback returns a promise, the plugin doesn't wait for it to be settled but instead calls the `completionHandler` right away. This causes iOS to take away execution time from the app if it is in the background, even though it is still within the granted 30 seconds [as per docs](https://developer.apple.com/documentation/backgroundtasks/choosing-background-strategies-for-your-app?language=objc), essentially delaying the promise to settle until the next time the app is given execution time.
With these changes, the `completionHandler` is called only after all promises have settled.
=> [@nativescript/firebase-messaging-core] feat: support async callbacks for messages and notification taps

packages/firebase-messaging-core/platforms/ios/src/NSCUNUserNotificationCenterDelegate.swift
`UNNotificationPresentationOptions.alert` is deprecated since iOS 14.0. This commit aims to fix this following the official documentation.
> Deprecated
> Use [list](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/list) and [banner](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/banner) instead.
https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/alert
=> fix(ios): cleaning firebase-messaging-core iOS build warnings

packages/firebase-core/index.android.ts, packages/firebase-core/index.ios.ts
When hot reloading using HMR, the default app is already set and is not resolved correctly.
=> fix(core): initializeApp default app not resolved
